const at = {
  MESSAGE_FETCH_MORE: 'MESSAGE_FETCH_MORE',
  MESSAGE_FETCH_MORE_SUCCESS: 'MESSAGE_FETCH_MORE_SUCCESS',
  MESSAGE_SOCKET_RECEIVE: 'MESSAGE_SOCKET_RECEIVE',
  ERROR_MESSAGE: 'ERROR_MESSAGE',
}

export default at

export const actionTypes = at
